# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-25 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('machine', models.CharField(blank=True, max_length=256, null=True)),
                ('from_city_id', models.IntegerField(blank=True, null=True)),
                ('to_city_id', models.IntegerField(blank=True, null=True)),
                ('from_city_name', models.CharField(blank=True, max_length=256, null=True)),
                ('to_city_name', models.CharField(blank=True, max_length=256, null=True)),
                ('table_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'route',
                'managed': False,
            },
        ),
    ]
