# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='EC2Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('public_dns', models.CharField(max_length=250)),
                ('public_ip', models.GenericIPAddressField()),
            ],
        ),
    ]
