# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-11 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('url_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('from_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_city', related_query_name='fromcity', to='flightmanage.City')),
                ('to_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_city', related_query_name='tocity', to='flightmanage.City')),
            ],
        ),
    ]
