# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flightmanage', '0002_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(blank=True, max_length=50, null=True)),
                ('task_status', models.CharField(choices=[('idle', 'not start'), ('running', 'running'), ('done', 'finished')], default='idle', max_length=10)),
                ('task_date', models.DateField(auto_now_add=True)),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('end_time', models.TimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightmanage.Route')),
            ],
        ),
        migrations.CreateModel(
            name='RouteTaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=50)),
                ('task_status', models.CharField(choices=[('idle', 'not start'), ('running', 'running'), ('done', 'finished')], default='idle', max_length=10)),
                ('task_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightmanage.Route')),
            ],
        ),
    ]
